version: "3"
services:
  groovy_context_manager:
    build: .
    volumes:
      - ./groovy_context_manager.py:/main.py
    command: python main.py
    environment:
      DISCORD_TOKEN: abc123
    restart: always
